name: Deploy to polymer@archlinux

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sync Files
        run: |
          # Sync root directly to /var/www/polymer
          rsync -av --delete --exclude '.git' --exclude 'node_modules' --exclude '.next' ./ /var/www/polymer/

      - name: Install Dependencies
        working-directory: /var/www/polymer
        run: pnpm install --no-frozen-lockfile

      - name: Run Migrations
        working-directory: /var/www/polymer
        env:
          DATABASE_URI: "${{ secrets.DATABASE_URI }}"
          PAYLOAD_SECRET: "${{ secrets.PAYLOAD_SECRET }}"
        run: pnpm payload migrate

      - name: Build App
        working-directory: /var/www/polymer
        env:
          DATABASE_URI: "${{ secrets.DATABASE_URI }}"
          PAYLOAD_SECRET: "${{ secrets.PAYLOAD_SECRET }}"
        run: pnpm run build

      - name: Start App
        working-directory: /var/www/polymer
        run: |
          pm2 describe polymer > /dev/null && pm2 reload polymer || pm2 start "pnpm start" --name "polymer"
          pm2 save
